name: test_prj
description: Test Flutter project.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=2.14.4 <3.0.0'

dependencies:
  flutter:
    sdk: flutter

  provider: ^6.0.1
  gap: ^2.0.0
  carousel_slider: ^4.0.0
  flutter_layout_grid: ^1.0.3
  line_icons: ^2.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  lints: ^1.0.1

flutter:
  uses-material-design: true
